language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: clang
    before_install:
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
    - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" | sudo
      tee -a /etc/apt/sources.list
    - echo "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main" |
      sudo tee -a /etc/apt/sources.list
    - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
    install:
    - sudo apt-get update
    - sudo apt-get install -y libboost-filesystem-dev
    - sudo apt-get install -y --only-upgrade cmake
    - sudo apt-get install -y clang-3.9-dev llvm-3.9-dev libboost-thread-dev
  - os: osx
    install:
    - brew install llvm --with-clang --with-rtti
    - brew link llvm --overwrite --force
    - brew install protobuf
script:
- mkdir -p build/Release && cd build/Release
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake ../../ -DCMAKE_BUILD_TYPE=Release; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ../../ -DCMAKE_BUILD_TYPE=Release -DUSE_LOCAL_PROTOBUF=ON; fi
- make
- make test
- zip -r autoffi-${TRAVIS_OS_NAME}.zip affc libcxx clang
deploy:
  provider: releases
  api_key:
    secure: g22TCNNsDKDBE7oV0MmVqar45s0IFZw1C9V46wvMzJKd2lxuzxjZKj3BUUukwUGzoLaH5W20mT0IkHzoq1OekFselRATKCcv+ehiUbOWd+V78qMtjGf2YOTcyb2xOcI92hl1+Rt8M/EMzITJ1NB/JmKW7fUHZFDqKs4gGw+K9rbpmhFwEVcDKcxrzMd20lCoLVB3BkAHvuQ7IfZuMkn2u7yKgDcQa+jqsaItT1lGeRUYmwtxXu9+eKbUyr1JdrlP3IsFaLDhJIPhb6LP9xfG5eKc7SAGSgC7tv3EijrpQ1paZBwrMvmd2Cfk2J9Wep/uqzcqNkN00XIT6b12yak7Toa9flTu5MotV0mH2/DGi++gVjVAqgiCa9YDNXqkp2kMqg7/Z/clp+ze3NToRiXjNP8QAxd0FyapIPqQbWbSNqIFBe+R7AlFfDXteTALwGqHt2leYEhDNy2xvvRU6+mVmxq6JlqpAxUXj4tUpCqO6fngEK4hoQWV7Vlr34g41dm//aM2SFtjLyFJJ62sMSDBPwVeo75/pVHw2/tVPfF9oGUWgr/nmW/Xnb2BH/YIgVaWMoXubQz+iKJLi3COWZsPN1FsinspukSbZeHJU9waVhWi2elrUq1Yh1Ohi/QqEMvRC79eftr6nZ0IwYG0syvopBi06dBFMBhTtuzMH+KbS34=
  skip_cleanup: true
  file:
  - autoffi-${TRAVIS_OS_NAME}.zip
  on:
    tags: true
